### ISSUE TITLE
Code re-structure

### ISSUE THREAD

**Issue by glensc** [ZeroQI/YouTube-Agent.bundle#104]
The current code is all in a single `__init__.py` file, which is very difficult to read.

What do you think of splitting the code into more files so that `__init__.py` contains only the public API needed to run the plugin?

From My understanding the `__init__.py` should only expose these symbols:

```py
def Start():
class YouTubeSeriesAgent(Agent.TV_Shows):
class YouTubeMovieAgent(Agent.Movies):
```

**Comment by glensc** [comment]
Seems Plex still has Python 2.7, so relative imports don't exist. however seems import path is hacked to include current plugin path in it:

```diff
--- /dev/null
+++ b/Contents/Code/a.py
@@ -0,0 +1 @@
+bar = 42

--- a/Contents/Code/__init__.py
+++ b/Contents/Code/__init__.py
@@ -10,6 +10,12 @@ import urllib2              #
 from   lxml    import etree #
 from   io      import open  # open

+try:
+    import a
+    Log.Info('answer to everything: %s' % a.bar)
+except Exception as e:
+    Log.Error('answer to everything: %s' % str(e))
+
```

results in `com.plexapp.agents.youtube.log`:

```
2022-05-08 00:40:38,654 (-49066234) :  INFO (__init__:15) - answer to everything: 42
```

**Comment by ZeroQI** [comment]
Not 100% sure Python version is the same across all platform, and wouldn't change in the future, especially since Python 2 is end of life...

I can't troubleshoot on my phone if it is split and would stop supporting, and movie and series support quite overlapp, would have to have to change code in two places for no reason while i have no time to dedicate to this agent...

I can't picture the intent or implications of: "Seems Plex still has Python 2.7, so relative imports don't exist. however seems import path is hacked to include current plugin path in it:"...

https://forums.plex.tv/t/plugin-development-documentation/107751/2?u=dane22 you have the framework documentation pdf that define how to code agents, a petty good help to write agents

New Plex agents are using C++ and seem like third party agents will be phased out, and you need old style libraries to use them as new type libraries don't allow Python agents to run...

**Comment by glensc** [comment]
> Not 100% sure Python version is the same across all platform, and wouldn't change in the future, especially since Python 2 is end of life...

I don't think this is an issue, as seems every plugin is able to specify 	`PlexFrameworkVersion` in `info.plist`:
- https://github.com/ZeroQI/YouTube-Agent.bundle/blob/f6749bda61c3c8ebe6004a5f1de6458070b2af89/Contents/Info.plist#L7-L8

So this seem to correspond to `Framework.bundle/Contents/Resources/Versions/2` in `Plex Media Server.app/Contents/Resources/Plug-ins-1a38e63c6/Framework.bundle`

So, if they ever provide Python 3 compatible `Framework.bundle`, they will add new `Versions/3`

**Comment by glensc** [comment]
> I can't picture the intent or implications of: "Seems Plex still has Python 2.7, so relative imports don't exist. however seems import path is hacked to include current plugin path in it:"...

I just tried to say relative imports don't work with `PlexFrameworkVersion=2` (`import .a`), but absolute imports load the module from the plugin directory and showed it with an example.

**Comment by glensc** [comment]
> and movie and series support quite overlap, would have to change code in two places for no reason 

an unclear statement, if you have duplicate code (copy-paste) then it's easier to compare two files, than different regions in the same file, using `diff` or any IDE to compare files.

but that itself seems like [code smell], should refactor with [extract method] to move common code to single function.

bonus: [jetbrains idea extract method] is even able to detect duplicate code and offer to extract them both.

[code smell]: https://en.wikipedia.org/wiki/Code_smell
[extract method]: https://refactoring.guru/extract-method
[jetbrains idea extract method]: https://www.jetbrains.com/help/idea/extract-method.html

**Comment by ZeroQI** [comment]
I do not reproduce issues as I do not use Plex anymore and never used this agent for myself. I live edit code on my phone most of times. I need to be able to follow all code in one go. I have invited you as collaborator since you did more pull request than anybody else and this is my least followed project with Lambda... On PC when too tricky I use Notepad++, nothing else...

**Comment by glensc** [comment]
indeed it's very peculiar to consider long files and long functions with duplicate logic more readable/maintainable!

usually, if someone writes so, they intend it as sarcasm:
- https://medium.com/@Superbinary/how-to-become-an-irreplaceable-front-end-talent-in-the-company-f037e894265e

**Comment by ZeroQI** [comment]
I am not for duplicated logic, but shorter length overall
Just creating a new function called once only seem ludicrous to me, but repetitive code that cannot be regrouped by conditional commands I have no issue with, as you should only modify at one place only.
Code less than 1k or 2k lines long do not really benefit for splitting up and excessive functions as you just increase the line count, I want the shortest code for the job ideally...

**Comment by ZeroQI** [comment]
I understand the sarcasm in the link given, and have taken the split file approach in HAMA so we have one file per metadata source, but if you look at all agents for Plex, most use single files as the code is very short.

I do use functions when appropriate, I think Dict() is the most used as it avoid array keys errors and allow to shorten the main code dramatically...

Now just externalizing a function used once to have a fancy name, a comment is more useful...

I don't think my code is that bad...
