### ISSUE TITLE
Multiple Playlist for Same Channel Creates Multiple TV Series Instead of Multiple Seasons

### ISSUE THREAD

**Issue by KillzMckinzie** [ZeroQI/YouTube-Agent.bundle#143]
This may be by design, but I was not able to get a channel with multiple playlists to be a single tv series with multiple seasons in Plex. No issues with this plugin at all, everything works perfect, except this single issue. Just to confirm my format was correct, I copied the exact playlists and channel from the example provided on main page below. Even with the exact same channel, channel ID, subfolders and videos + IDs, plex is still not creating a single tv series with multiple seasons: 

CaRtOoNz [UCdQWs2nw6w77Rw0t-37a4OA]/
- Ben and Ed/
  - Ben and Ed _ 'My Zombie Best Friend!' (I Didn't Need Those Legs Anyway!) [fRFr7L_qgEo].mkv
  - Ben and Ed _ 'Clownin Around!' (F_ck You Neck-Beard!) [Nh9eILgD5N4].mkv
- Golf With Your Friends/
  - Golf With Friends _ HOLE IN ONE...THOUSAND! (w_ H2O Delirious, Bryce, & Ohmwrecker) [81er8CP24h8].mkv
  - Golf With Friends _ GOLF LIKE AN EGYPTIAN! (w_ H2O Delirious, Bryce, & Ohmwrecker) [gKYid-SjDiE].mkv

![image](https://github.com/ZeroQI/YouTube-Agent.bundle/assets/47094613/024d09bb-4b14-4400-aae4-9104c0f2cb76)

Ignore numbers, I stopped the download after a few videos downloaded. I only needed a few to test with, but as you can see, it's showing up as different series and not as a single channel with multiple seasons.

Again this might be by design but just wanted to confirm or ask for help if I am doing something wrong. Let me know if you need any specific logs or screenshots from me, thanks!.

**Comment by ZeroQI** [comment]
"I was not able to get a channel with multiple playlists to be a single tv series with multiple seasons in Plex": 'Season' is mentioned exactly once in the readme to differentiate scanner and agent issues, an nowhere does it gives any indication it is supported. Channel series use the year as season by design... 

You could use season numbering "Season 1 Ben and Ed" but haven't tested, however using a series folder with Playlist Id and grouped in a collection would be the most standard way

**Comment by ZeroQI** [comment]
Try putting the Playlist Id on both subfolders, it should create a collection and treat them as separate series and Playlist Id are more precise
