### ISSUE TITLE
Items no showing 

### ISSUE THREAD

**Issue by vic1707** [ZeroQI/YouTube-Agent.bundle#33]
Hi i just found your projet and it seems fantastic.
I tried it but nothing is detected on my plex library... 
The files look like that :
`
-- Bob Lennon [UCo0U1tbk3YbqiLDhkeWOviQ]
     ¦- The Headliner
          ¦- LES NEWS !! SUR BOBFMTV !!! -Headliner- Ep.1_3 avec Bob Lennon[h7h_r1aa5cM].mp4

-- Joueur Du Grenier [UC_yP2DpIgs5Y1uWC0T03Chw]
    ¦- Joueur du Grenier 
        ¦- Joueur du grenier - MEN IN BLACK [8VRICg4bLQ8].mp4
`

I've installed your plugin in the right place, created the library and it uses the plugin. 
I didn't really understand what I have to do, if I need to install something else ?
The file were downloaded from NewPipe (Android) and I've add manualy the id throught the URL of the vidéos (maybe it's why it's not working ?)

Also is there a way to not use the real name of the vidéo, because the original one for the first file contains à "/" ( real name "LES NEWS !! SUR BOBFMTV !!! -Headliner- Ep.1/3 avec Bob Lennon" instead of "LES NEWS !! SUR BOBFMTV !!! -Headliner- Ep.1_3 avec Bob Lennon") ...

**Comment by ZeroQI** [comment]
Naming seem good.
The agent uses the video id so no issue with OS forbidden chars in titles or renaming the files...

" nothing is detected on my plex library" => are the files SHOWING?
- If so, please attach the agent logs
- If not, well that explain, you are meant to use the Absolute Series Scanner as specified in the readme requirements, and feel free to donate (got a 15 and a 5 euros donation to date)

**Comment by vic1707** [comment]
The files aren't showing at all, the library is empty.
OK how To install the Absolute Series scanner ?
My PMS is on a freenas jail and I don't have either the "/var/lib" directory and "[...]/ Plex Media Server/Scanners" 

A screenshot of the directory "[...]/Plex Media Server/" (sorry for the quality I'm actually at school with only a Phone) 
![Screenshot_2019-11-07-10-37-20-209_com sonelli juicessh](https://user-images.githubusercontent.com/28602203/68377417-a115f580-014a-11ea-8a90-4fa827d0cbbc.jpg)

**Comment by ZeroQI** [comment]
Where is your message from this morning? Deleted ?
https://github.com/ZeroQI/Absolute-Series-Scanner readme:

Install / Update
- Download https://raw.githubusercontent.com/ZeroQI/Absolute-Series-Scanner/master/Scanners/Series/Absolute%20Series%20Scanner.py
- Save into [...]/Plex Media Server/Scanners/Series/Absolute Series Scanner.py Note:
- "Scanners" and "Series" folder are not created by default and will need to be created.
- "Scanners" folder will be at the same level as "Plug-in Support" folder (in other words the same parent directory)
- "Absolute Series Scanner.py" resides in Series folder, do not create an additional folder not listed like "absolute-series-scanner-master" and add the correct permissions on the init.py file. This should be done with chmod +x under linux
- Once the scanner is installed correctly, when creating a library you can select the custom scanner, otherwise the drop-down selection list is not shown when creating a TV Series library on the advanced tab.

**Comment by vic1707** [comment]
It worked thanks
