### ISSUE TITLE
[Feature Request] Add support for music libraries

### ISSUE THREAD

**Issue by fbjerggaard** [ZeroQI/YouTube-Agent.bundle#43]
It would be great if this plugin also supported music libraries.

**Comment by ZeroQI** [comment]
It support playlists and channels already so please explain what naming you tried that failed gathering metadata?
Please include the scanner logs from your music library

**Comment by mylogon341** [comment]
I would have hoped this could have worked somehow. There are non-music videos that I have ripped the audio from (with the `-x` param in yt-dlp) and would have liked to have a music library in plex so I can listen to those videos in plexamp. Some use cases might be include any spoken content such as podcast-type videos, meditation videos, or just about any other video that you're interested in listening to only.

As it stands I can create a tv library and just lock the device a press play again with it in the background, but it would have been nice to have an agent on that music library to hook up those videos. I'll think over my situation and re-approach, but this was just my first instinct.

I know it's quite a niche use case, but this seems more like a "legit" use case that just ripping music.

**Comment by ZeroQI** [comment]
It could be done using Lambda agent as a basis to add YouTube audio library part most likely, but I am not interested in coding it. I am not even using plex anymore since years, still installed on my synology NAS with a not up to date Hama agent, YouTube agent isn't even installed, never used it for myself, I thought I would be popular but that was a mistake...
