### ISSUE TITLE
Wrong episode number

### ISSUE THREAD

**Issue by pekempy** [ZeroQI/YouTube-Agent.bundle#50]
Hey,

I've downloaded a [YouTube playlist ](https://www.youtube.com/playlist?list=PL_lgEqY9K6UXUVco5XysDNAeUnCqSFcqS) using YouTubeDL with the following format:
`date - title [video-id].ext `
I have had to edit the title as it contained [Series] in it which messed with the youtube ID part, but have one episode still wrong.

One episode in question (Episode 47) is showing in Plex as episode 201 for some reason
As you can see in [this image](https://i.imgur.com/QATz5UV.png) episode 47 shows as episode 201. I can't seem to find a way to edit this, and refreshing metadata doesn't succeed.
File name is `20190220 - 5 Friends & A Horde of Foxes - Rimworld Ice Sheet Tribal Ep. 47 [QRPAe258Sfc].mp4`

The ID is correct and in the playlist it comes up as episode 47, so unsure why this is happening?

**Comment by ZeroQI** [comment]
Seasons and Episode numbers are chosen by the SCANNER (as stated in the first line of the scanner read-me) 
- Refreshing metadata will NEVER change the episode or season number
- the scanner logs are missing, which is a shame since they would indicate the reason for the choice, possibly the file timestamp

Closing as episode number is scanner related and series folder name is missing so i cannot tell if you did put the playlist id [PL_lgEqY9K6UXUVco5XysDNAeUnCqSFcqS] correctly...
